/**
 * Common Slack emoji shortcode to Unicode emoji mapping
 *
 * Based on https://github.com/iamcal/emoji-data
 * Only includes most commonly used emojis to keep bundle size small
 */

export const SLACK_EMOJI_MAP: Record<string, string> = {
  // Hearts & Love
  'heart': '❤️',
  'blue_heart': '💙',
  'green_heart': '💚',
  'yellow_heart': '💛',
  'purple_heart': '💜',
  'orange_heart': '🧡',
  'black_heart': '🖤',
  'white_heart': '🤍',
  'brown_heart': '🤎',
  'sparkling_heart': '💖',
  'heartpulse': '💗',
  'heartbeat': '💓',
  'revolving_hearts': '💞',
  'two_hearts': '💕',
  'heart_decoration': '💟',
  'heart_eyes': '😍',
  'kissing_heart': '😘',
  'cupid': '💘',
  'gift_heart': '💝',
  'broken_heart': '💔',

  // Faces & Emotions
  'smile': '😄',
  'smiley': '😃',
  'grinning': '😀',
  'blush': '😊',
  'relaxed': '☺️',
  'wink': '😉',
  'stuck_out_tongue_winking_eye': '😜',
  'stuck_out_tongue': '😛',
  'stuck_out_tongue_closed_eyes': '😝',
  'joy': '😂',
  'laughing': '😆',
  'sweat_smile': '😅',
  'grin': '😁',
  'thinking_face': '🤔',
  'face_with_raised_eyebrow': '🤨',
  'neutral_face': '😐',
  'expressionless': '😑',
  'no_mouth': '😶',
  'rolling_eyes': '🙄',
  'smirk': '😏',
  'persevere': '😣',
  'disappointed_relieved': '😥',
  'open_mouth': '😮',
  'zipper_mouth_face': '🤐',
  'hushed': '😯',
  'sleepy': '😪',
  'tired_face': '😫',
  'sleeping': '😴',
  'relieved': '😌',
  'nerd_face': '🤓',
  'sunglasses': '😎',
  'dizzy_face': '😵',
  'astonished': '😲',
  'worried': '😟',
  'frowning': '☹️',
  'anguished': '😧',
  'grimacing': '😬',
  'confused': '😕',
  'slightly_frowning_face': '🙁',
  'cry': '😢',
  'sob': '😭',
  'scream': '😱',
  'confounded': '😖',
  'disappointed': '😞',
  'sweat': '😓',
  'weary': '😩',
  'triumph': '😤',
  'rage': '😡',
  'angry': '😠',
  'smiling_imp': '😈',
  'clap': '👏',
  'pray': '🙏',
  'raised_hands': '🙌',
  'wave': '👋',
  '+1': '👍',
  'thumbsup': '👍',
  '-1': '👎',
  'thumbsdown': '👎',
  'ok_hand': '👌',
  'facepunch': '👊',
  'fist': '✊',
  'v': '✌️',
  'point_up': '☝️',
  'point_right': '👉',
  'point_down': '👇',
  'point_left': '👈',

  // Symbols
  'star': '⭐',
  'sparkles': '✨',
  'boom': '💥',
  'fire': '🔥',
  'tada': '🎉',
  'confetti_ball': '🎊',
  'balloon': '🎈',
  'trophy': '🏆',
  'medal': '🏅',
  'checkmark': '✅',
  'white_check_mark': '✅',
  'heavy_check_mark': '✔️',
  'x': '❌',
  'heavy_multiplication_x': '✖️',
  'bangbang': '‼️',
  'interrobang': '⁉️',
  'question': '❓',
  'grey_question': '❔',
  'grey_exclamation': '❕',
  'exclamation': '❗',
  'warning': '⚠️',
  'sos': '🆘',
  'no_entry': '⛔',
  'no_entry_sign': '🚫',

  // Objects & Things
  'bulb': '💡',
  'brain': '🧠',
  'eyes': '👀',
  'eye': '👁️',
  'memo': '📝',
  'pencil2': '✏️',
  'book': '📖',
  'books': '📚',
  'bookmark': '🔖',
  'link': '🔗',
  'paperclip': '📎',
  'pushpin': '📌',
  'rocket': '🚀',
  'dart': '🎯',
  'hourglass': '⌛',
  'alarm_clock': '⏰',
  'calendar': '📅',
  'date': '📅',
  'moneybag': '💰',
  'gem': '💎',
  'gift': '🎁',
  'birthday': '🎂',
  'coffee': '☕',
  'tea': '🍵',
  'pizza': '🍕',
  'hamburger': '🍔',
  'beer': '🍺',
  'beers': '🍻',
  'wine_glass': '🍷',
  'cocktail': '🍸',
  'tropical_drink': '🍹',

  // Nature
  'sunny': '☀️',
  'rainbow': '🌈',
  'cloud': '☁️',
  'umbrella': '☂️',
  'snowflake': '❄️',
  'zap': '⚡',
  'ocean': '🌊',
  'evergreen_tree': '🌲',
  'deciduous_tree': '🌳',
  'cactus': '🌵',
  'seedling': '🌱',
  'blossom': '🌼',
  'cherry_blossom': '🌸',
  'rose': '🌹',
  'sunflower': '🌻',
  'tulip': '🌷',

  // Animals
  'dog': '🐶',
  'cat': '🐱',
  'mouse': '🐭',
  'hamster': '🐹',
  'rabbit': '🐰',
  'fox_face': '🦊',
  'bear': '🐻',
  'panda_face': '🐼',
  'koala': '🐨',
  'tiger': '🐯',
  'lion': '🦁',
  'cow': '🐮',
  'pig': '🐷',
  'frog': '🐸',
  'monkey_face': '🐵',
  'see_no_evil': '🙈',
  'hear_no_evil': '🙉',
  'speak_no_evil': '🙊',
  'bird': '🐦',
  'penguin': '🐧',
  'chicken': '🐔',
  'hatching_chick': '🐣',
  'fish': '🐟',
  'dolphin': '🐬',
  'whale': '🐳',
  'bug': '🐛',
  'snail': '🐌',
  'bee': '🐝',
  'butterfly': '🦋',
};

/**
 * Convert Slack emoji shortcode to Unicode emoji
 * @param shortcode - Emoji shortcode without colons (e.g., "heart", "thumbsup")
 * @returns Unicode emoji or the original shortcode with colons if not found
 */
export function slackEmojiToUnicode(shortcode: string): string {
  return SLACK_EMOJI_MAP[shortcode] || `:${shortcode}:`;
}

/**
 * Format Slack permalink URL
 * @param workspaceUrl - Base Slack workspace URL (e.g., "https://yourworkspace.slack.com")
 * @param channelId - Channel ID
 * @param messageTs - Message timestamp (with decimal point)
 * @returns Formatted Slack permalink
 */
export function formatSlackPermalink(
  workspaceUrl: string,
  channelId: string,
  messageTs: string
): string {
  // Convert timestamp format: "1234567890.123456" -> "p1234567890123456"
  const pTs = 'p' + messageTs.replace('.', '');
  return `${workspaceUrl}/archives/${channelId}/${pTs}`;
}
