-- Personal calendar feeds: each member gets a secret token for a subscribable iCalendar URL
-- (/api/calendar/feed/<token>.ics) listing the prickles they host and the ones they've committed
-- to. Calendar apps fetch the feed without a session, so the token is the only credential: the
-- route looks it up with the service role and serves that one member's events. "Generate new
-- link" replaces the token, which cuts off every calendar subscribed to the old one.
--
-- LOCAL layer: owned by this app, normal CRUD, never reprocessed.
CREATE TABLE calendar_feed_tokens (
  member_id UUID PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
  -- 32 hex chars (128 random bits), generated by the app.
  token TEXT NOT NULL UNIQUE CHECK (token ~ '^[0-9a-f]{32}$'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE calendar_feed_tokens IS
  'LOCAL: one secret token per member for their subscribable calendar feed
   (/api/calendar/feed/<token>.ics: hosted + committed prickles). Replacing the token revokes the
   old feed URL. The feed route reads this with the service role; members see only their own row.';

ALTER TABLE calendar_feed_tokens ENABLE ROW LEVEL SECURITY;

-- Owner via current_member_id(), admin via is_admin() (which also covers sudo, since a sudo'd
-- request runs under the real admin's session). Same conventions as 20260926000600.
CREATE POLICY "View own calendar feed token, admins view all" ON calendar_feed_tokens
  FOR SELECT TO authenticated
  USING (member_id = (SELECT public.current_member_id()) OR (SELECT public.is_admin()));
CREATE POLICY "Create own calendar feed token, admins create any" ON calendar_feed_tokens
  FOR INSERT TO authenticated
  WITH CHECK (member_id = (SELECT public.current_member_id()) OR (SELECT public.is_admin()));
CREATE POLICY "Replace own calendar feed token, admins replace any" ON calendar_feed_tokens
  FOR UPDATE TO authenticated
  USING (member_id = (SELECT public.current_member_id()) OR (SELECT public.is_admin()))
  WITH CHECK (member_id = (SELECT public.current_member_id()) OR (SELECT public.is_admin()));
